### ISSUE TITLE
Create Packer template for Zabbix Proxy image in AWS

### ISSUE THREAD

**Issue by edikmkoyan** [edikmkoyan/terraform-aws-zabbix#1]
For some reason zabbix proxy ami is missing for. We need to write a packer template that packs the zabbix proxy ami.
https://www.zabbix.com/cloud_images
https://www.zabbix.com/download?zabbix=5.2&os_distribution=centos&os_version=8&db=mysql&ws=apache

**Comment by narek-ham** [comment]
- First did a simple test by creating zabbix agent image, eventually succeeded ))

Interesting point: looks like it needs `python-netaddr` to be installed locally and fails with `"sudo: a password is required\n
"`

./roles/zabbix_agent/tasks/main.yml:
```
- name: "Install local python-netaddr package"
  pip:
    name: netaddr
    state: present
  register: zabbix_python_netaddr_package_installed
  until: zabbix_python_netaddr_package_installed is succeeded
  delegate_to: localhost
  run_once: True
  become: "{{ zabbix_agent_become_on_localhost }}"
  when:
    - zabbix_install_pip_packages | bool
    - ansible_all_ipv4_addresses is defined or (zabbix_agent_ip is not defined and total_private_ip_addresses is defined)`
```

```
    amazon-ebs.basic-example: FAILED - RETRYING: Install local python-netaddr package (3 retries left).
    amazon-ebs.basic-example: FAILED - RETRYING: Install local python-netaddr package (2 retries left).
    amazon-ebs.basic-example: FAILED - RETRYING: Install local python-netaddr package (1 retries left).
    amazon-ebs.basic-example: fatal: [default]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Running with `sudo` failed at another point but installed the package, so another try without `sudo` succeeded:
```
narek@narek:~/DevOps/Packer$ sudo packer build   test.pkr.hcl
amazon-ebs.basic-example: output will be in this color.
...
   amazon-ebs.basic-example: < TASK [Gathering Facts] >
...
    amazon-ebs.basic-example: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /root/.ansible/tmp `\"&& mkdir \"` echo /root/.ansible/tmp/ansible-tmp-1615153595.33-11604-145391865692481 `\" && echo ansible-tmp-1615153595.33-11604-145391865692481=\"` echo /root/.ansible/tmp/ansible-tmp-1615153595.33-11604-145391865692481 `\" ), exited with result 1", "unreachable": true}
```

- Creating zabbix-proxy failed with the following:
~~~
    amazon-ebs.basic-example: < TASK [./roles/zabbix_proxy : Get the file for schema.sql] >
...
    amazon-ebs.basic-example: fatal: [default]: FAILED! => {"changed": false, "cmd": "ls -1 /usr/share/doc/zabbix-proxy-mysql/schema.sq*", "delta": "0:00:00.003720", "end": "2021-03-07 22:28:39.847295", "msg": "non-zero return code", "rc": 2, "start": "2021-03-07 22:28:39.843575", "stderr": "ls: cannot access '/usr/share/doc/zabbix-proxy-mysql/schema.sq*': No such file or directory", "stderr_lines": ["ls: cannot access '/usr/share/doc/zabbix-proxy-mysql/schema.sq*': No such file or directory"], "stdout": "", "stdout_lines": []}

~~~
Will retry and try to resolve.

@edikmkoyan Do we need to keep track of this type of information?
